site_name: Papa Francky's HowTos

theme:
  name: material
  language: en
  direction: ltr
  features:
    - content.code.copy
    - content.code.annotate
  icon:
    logo: fontawesome/solid/poo
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16
  favicon: images/poo.ico
  palette:

    # Palette toggle for dark mode
    - scheme: slate
      primary: blue grey
      font:
        text: Roboto
        code: Roboto mono
      toggle:
        icon: material/lightbulb-outline
        name: Switch to light mode

    # Palette toggle for light mode
    - scheme: default
      primary: orange
      font:
        text: Roboto
        code: Roboto mono
      toggle:
        icon: material/lightbulb 
        name: Switch to dark mode

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - tables
  - footnotes